[game]
board_size = 20
num_moves = 30433
num_pieces = 21
num_piece_orientations = 91
move_data_file = "static/move_data/full.bin"

[network]
model_class = "resnet"
main_body_channels = 96
residual_blocks = 10
value_head_channels = 64
value_head_flat_layer_width = 64
policy_head_channels = 64
policy_convolution_kernel = 3

[training_offline]
device = "mps"
learning_rate = 1e-3
policy_loss_weight = 0.158
batch_size = 128
in_memory_shuffle_file_count = 3
num_workers = 2
prefetch_factor = 60
game_data_directory = "s3://alpha-blokus/full_v2/games/"
local_game_mirror = "/Users/shivamsarodia/Dev/AlphaBlokus/data/s3_mirrors/full_v2/games"
model_directory = "s3://alpha-blokus/full_v2/models_simulated/"
training_directory = "s3://alpha-blokus/full_v2/training_simulated/"
output_name = "10m_10block_96chan"
