num_concurrent_games = 32
duration_seconds = 1200

[observability.metrics]
type = "prometheus"

[observability.logging]
type = "console"

[mcts_recorder]
type = "disabled"

[[inference]]
name = "default"
model_path = "s3://alpha-blokus/full/models/04213034.onnx"
batch_size = 8
executor = { type = "tensorrt", max_batch_size = 8, pool_size = 32 }

[[agents.QuadArena]]
name = "pentobi_level_1_04213034"
type = "pentobi"
binary_path = "/workspace/pentobi/pentobi_gtp/pentobi-gtp"
opening_book = "/workspace/pentobi/opening_books/book_classic.blksgf"
level = 1

[[agents.QuadArena]]
name = "pentobi_level_2_04213034"
type = "pentobi"
binary_path = "/workspace/pentobi/pentobi_gtp/pentobi-gtp"
opening_book = "/workspace/pentobi/opening_books/book_classic.blksgf"
level = 2

[[agents.QuadArena]]
name = "mcts_low_temp_04213034"
type = "mcts"
inference_config_name = "default"
fast_move_probability = 0.0
fast_move_num_rollouts = 500
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 35
move_selection_temperature = 0.3
default_exploitation_value = { type = "network_value" }

[[agents.QuadArena]]
name = "mcts_high_temp_04213034"
type = "mcts"
inference_config_name = "default"
fast_move_probability = 0.0
fast_move_num_rollouts = 500
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 100
move_selection_temperature = 1.0
default_exploitation_value = { type = "network_value" }

[game]
board_size = 20
num_moves = 30433
num_pieces = 21
num_piece_orientations = 91
move_data_file = "static/move_data/full.bin"
