[game]
board_size = 20
num_moves = 30433
num_pieces = 21
num_piece_orientations = 91
move_data_file = "static/move_data/full.bin"

[network]
model_class = "resnet"
main_body_channels = 64
residual_blocks = 10
value_head_channels = 16
value_head_flat_layer_width = 64
policy_head_channels = 64
policy_convolution_kernel = 3

[training]
device = "cuda"
num_epochs = 1
learning_rate = 1e-3
batch_size = 128
policy_loss_weight = 0.158
ignore_invalid_moves = true
simulated = false
sampling_ratio = 2.0
window_size = 300000
min_samples_for_save = 30000
poll_interval_seconds = 10

[directories]
game_data_directory = "s3://alpha-blokus/full_v2/games/"
model_directory = "s3://alpha-blokus/full_v2/models/"
training_directory = "s3://alpha-blokus/full_v2/training/"
