[game]
board_size = 20
num_moves = 30433
num_pieces = 21
num_piece_orientations = 91
move_data_file = "static/move_data/full.bin"

[network]
model_class = "resnet_conv_value"
main_body_channels = 64
residual_blocks = 10
value_head_channels = 64
value_head_flat_layer_width = 64
policy_head_channels = 64
policy_convolution_kernel = 3

[training]
output_name = "conv_value"
device = "mps"
num_epochs = 1
learning_rate = 1e-3
batch_size = 128
policy_loss_weight = 0.158
simulated = true
sampling_ratio = 2.0
window_size = 200000
min_samples_for_save = 100000000
poll_interval_seconds = 10

[directories]
game_data_directory = "s3://alpha-blokus/full_v2/games/"
model_directory = "s3://alpha-blokus/full_v2/models_simulated/"
training_directory = "s3://alpha-blokus/full_v2/training_simulated/"
