[game]
board_size = 20
num_moves = 30433
num_pieces = 21
num_piece_orientations = 91
move_data_file = "static/move_data/full.bin"

[network]
model_class = "resnet"
main_body_channels = 128
residual_blocks = 12
value_head_channels = 32
value_head_flat_layer_width = 128
policy_head_channels = 128
policy_convolution_kernel = 3

[training_standalone]
device = "mps"
learning_rate = 1e-3
policy_loss_weight = 0.158
ignore_invalid_moves = true
num_epochs = 1
batch_size = 128
shuffle_buffer_file_count = 2
train_batches_per_test = 4
num_workers = 2
prefetch_factor = 60
remote_train_data_dir = "s3://alpha-blokus/full/games_04413189/"
remote_test_data_dir = "s3://alpha-blokus/full/games_04413189_b/"
local_game_mirror = "/Users/shivamsarodia/Dev/AlphaBlokus/data/s3_mirrors/full/games"
aim_repo_path = "/Users/shivamsarodia/Dev/AlphaBlokus/data/aim"
