[game]
board_size = 20
num_moves = 30433
num_pieces = 21
num_piece_orientations = 91
move_data_file = "static/move_data/full.bin"

[network]
model_class = "resnet_conv_value"
main_body_channels = 64
residual_blocks = 10
value_head_channels = 64
value_head_flat_layer_width = 64
policy_head_channels = 64
policy_convolution_kernel = 3

[training_standalone]
output_name = "conv_value"
device = "mps"
learning_rate = 1e-3
policy_loss_weight = 0.158
num_epochs = 3
batch_size = 128
shuffle_buffer_file_count = 2
num_workers = 2
prefetch_factor = 60
max_train_files = 201
remote_train_data_dir = "s3://alpha-blokus/full_v2/games/"
local_game_mirror = "/Users/shivamsarodia/Dev/AlphaBlokus/data/s3_mirrors/full_v2/games"
aim_repo_path = "/Users/shivamsarodia/Dev/AlphaBlokus/data/aim"
model_directory = "s3://alpha-blokus/full_v2/models_simulated/"
training_directory = "s3://alpha-blokus/full_v2/training_simulated/"