[game]
board_size = 20
num_moves = 30433
num_pieces = 21
num_piece_orientations = 91
move_data_file = "static/move_data/full.bin"

[network]
model_class = "resnet"
main_body_channels = 64
residual_blocks = 10
value_head_channels = 16
value_head_flat_layer_width = 64
policy_head_channels = 64
policy_convolution_kernel = 3

[training_standalone]
device = "mps"
learning_rate = 1e-3
policy_loss_weight = 0.158
num_epochs = 2
batch_size = 128
shuffle_buffer_file_count = 4
test_split_stride = 10
max_total_games = 1600000
num_tests_per_epoch = 5
remote_game_dir = "s3://alpha-blokus/full/games/"
local_game_mirror = "/Users/shivamsarodia/Dev/AlphaBlokus/data/s3_mirrors/full/games"
aim_repo_path = "/Users/shivamsarodia/Dev/AlphaBlokus/data/aim"
