num_concurrent_games = 1024

[observability.metrics]
type = "prometheus"

[observability.logging]
type = "console"

[mcts_recorder]
type = "disabled"

[[inference]]
name = "mcts_1"
model_path = "s3://alpha-blokus/full/models/01501053.onnx"
batch_size = 128
executor = { type = "tensorrt", max_batch_size = 128, pool_size = 32 }

[[inference]]
name = "mcts_2"
model_path = "s3://alpha-blokus/full/models/03032222.onnx"
batch_size = 128
executor = { type = "tensorrt", max_batch_size = 128, pool_size = 32 }

[[inference]]
name = "mcts_3"
model_path = "s3://alpha-blokus/full/models/04613343.onnx"
batch_size = 128
executor = { type = "tensorrt", max_batch_size = 128, pool_size = 32 }

[[agents.QuadArena]]
name = "random"
type = "random"

[[agents.QuadArena]]
name = "mcts_1"
type = "mcts"
inference_config_name = "mcts_1"
fast_move_probability = 0.0
fast_move_num_rollouts = 500
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 100
move_selection_temperature = 0.3

[[agents.QuadArena]]
name = "mcts_2"
type = "mcts"
inference_config_name = "mcts_2"
fast_move_probability = 0.0
fast_move_num_rollouts = 500
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 100
move_selection_temperature = 0.3

[[agents.QuadArena]]
name = "mcts_3"
type = "mcts"
inference_config_name = "mcts_3"
fast_move_probability = 0.0
fast_move_num_rollouts = 500
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 100
move_selection_temperature = 0.3

[game]
board_size = 20
num_moves = 30433
num_pieces = 21
num_piece_orientations = 91
move_data_file = "static/move_data/full.bin"
