num_concurrent_games = 1024

[observability.metrics]
type = "prometheus"

[observability.logging]
type = "console"

[mcts_recorder]
type = "disabled"

[[inference]]
name = "base"
model_path = "s3://alpha-blokus/full_v2/models_simulated/standalone_conv_value_position_1767949154.onnx"
batch_size = 64
# executor = { type = "tensorrt", max_batch_size = 64, pool_size = 32 }
executor = { type = "ort", execution_provider = "coreml" }

[[inference]]
name = "deep"
model_path = "s3://alpha-blokus/full_v2/models_simulated/standalone_resnet_bottleneck_deep_1767965772.onnx"
batch_size = 64
# executor = { type = "tensorrt", max_batch_size = 64, pool_size = 32 }
executor = { type = "ort", execution_provider = "coreml" }

[[inference]]
name = "fast"
model_path = "s3://alpha-blokus/full_v2/models_simulated/standalone_resnet_bottleneck_fast_1767969873.onnx"
batch_size = 64
# executor = { type = "tensorrt", max_batch_size = 64, pool_size = 32 }
executor = { type = "ort", execution_provider = "coreml" }

[[inference]]
name = "wide"
model_path = "s3://alpha-blokus/full_v2/models_simulated/standalone_resnet_bottleneck_wide_1767963083.onnx"
batch_size = 64
# executor = { type = "tensorrt", max_batch_size = 64, pool_size = 32 }
executor = { type = "ort", execution_provider = "coreml" }

[[agents.QuadArena]]
type = "mcts"
name = "2_base"
inference_config_name = "base"
fast_move_probability = 0.0
fast_move_num_rollouts = 500
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0.0
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 35
move_selection_temperature = 1.0

[[agents.QuadArena]]
type = "mcts"
name = "2_deep"
inference_config_name = "deep"
fast_move_probability = 0.0
fast_move_num_rollouts = 500
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0.0
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 35
move_selection_temperature = 1.0

[[agents.QuadArena]]
type = "mcts"
name = "2_fast"
inference_config_name = "fast"
fast_move_probability = 0.0
fast_move_num_rollouts = 500
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0.0
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 35
move_selection_temperature = 1.0

[[agents.QuadArena]]
type = "mcts"
name = "2_wide"
inference_config_name = "wide"
fast_move_probability = 0.0
fast_move_num_rollouts = 500
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0.0
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 35
move_selection_temperature = 1.0

[game]
board_size = 20
num_moves = 30433
num_pieces = 21
num_piece_orientations = 91
move_data_file = "static/move_data/full.bin"
