num_concurrent_games = 1024

[observability.metrics]
type = "prometheus"

[observability.logging]
type = "console"

[mcts_recorder]
type = "disabled"

[[inference]]
name = "10b_64c"
model_path = "s3://alpha-blokus/full_v2/models_simulated/10m_10block_64chan_1768656557.onnx"
batch_size = 64
executor = { type = "tensorrt", max_batch_size = 64, pool_size = 32 }
cache = { max_entries = 3000000 }

[[inference]]
name = "16b_64c"
model_path = "s3://alpha-blokus/full_v2/models_simulated/10m_16block_64chan_1768683553.onnx"
batch_size = 64
executor = { type = "tensorrt", max_batch_size = 64, pool_size = 32 }
cache = { max_entries = 3000000 }

[[inference]]
name = "10b_96c"
model_path = "s3://alpha-blokus/full_v2/models_simulated/10m_10block_96chan_1768713088.onnx"
batch_size = 64
executor = { type = "tensorrt", max_batch_size = 64, pool_size = 32 }
cache = { max_entries = 3000000 }

[[inference]]
name = "base"
model_path = "s3://alpha-blokus/full_v2/models_v2/"
batch_size = 64
executor = { type = "tensorrt", max_batch_size = 64, pool_size = 32 }
reload = { poll_interval_seconds = 60000 }
cache = { max_entries = 3000000 }

[[agents.QuadArena]]
type = "mcts"
name = "10b_64c"
inference_config_name = "10b_64c"
fast_move_probability = 0.0
fast_move_num_rollouts = 500
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0.0
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 35
move_selection_temperature = 1.0

[[agents.QuadArena]]
type = "mcts"
name = "16b_64c"
inference_config_name = "16b_64c"
fast_move_probability = 0.0
fast_move_num_rollouts = 500
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0.0
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 35
move_selection_temperature = 1.0

[[agents.QuadArena]]
type = "mcts"
name = "10b_96c"
inference_config_name = "10b_96c"
fast_move_probability = 0.0
fast_move_num_rollouts = 500
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0.0
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 35
move_selection_temperature = 1.0

[[agents.QuadArena]]
type = "mcts"
name = "base"
inference_config_name = "base"
fast_move_probability = 0.0
fast_move_num_rollouts = 500
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0.0
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 35
move_selection_temperature = 1.0

[game]
board_size = 20
num_moves = 30433
num_pieces = 21
num_piece_orientations = 91
move_data_file = "static/move_data/full.bin"
