num_concurrent_games = 1024
# duration_seconds = 60

[observability.metrics]
type = "prometheus"

[observability.logging]
type = "console"

[mcts_recorder]
type = "disabled"

[[inference]]
name = "default"
# model_path = "s3://alpha-blokus/full_v2/models_untrained/res_net_cvp_auto_quantized.onnx"
model_path = "s3://alpha-blokus/full_v2/models_simulated/06081134_conv_value_position_1767797812.onnx"
batch_size = 128
executor = { type = "tensorrt", max_batch_size = 128, pool_size = 32 }
reload = { poll_interval_seconds = 60 }
cache = { max_entries = 5000000 }

[agents.Single]
type = "mcts"
fast_move_probability = 0.8
fast_move_num_rollouts = 100
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0.25
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 35
move_selection_temperature = 1.0
inference_config_name = "default"

[game]
board_size = 20
num_moves = 30433
num_pieces = 21
num_piece_orientations = 91
move_data_file = "static/move_data/full.bin"