num_concurrent_games = 128

[mcts_recorder]
data_directory = "data/scrap/games/"
flush_row_count = 50

[[inference]]
name = "default"
model_path = "data/scrap/models/"
batch_size = 32
executor = { type = "ort" }
reload = { poll_interval_seconds = 5 }

[agents.Single.MCTS]
fast_move_probability = 0.8
fast_move_num_rollouts = 100
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0.25
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 10
move_selection_temperature = 1.0
inference_config_name = "default"

[game]
board_size = 10
num_moves = 6233
num_pieces = 21
num_piece_orientations = 91
move_data_file = "static/move_data/half.bin"
