num_concurrent_games = 1024

[observability.metrics]
type = "prometheus"

[observability.logging]
type = "console"

[mcts_recorder]
type = "disabled"

[[inference]]
name = "00500124"
model_path = "s3://alpha-blokus/half/models/00500124.onnx"
batch_size = 128
executor = { type = "tensorrt", max_batch_size = 128, pool_size = 32 }

[[inference]]
name = "01000230"
model_path = "s3://alpha-blokus/half/models/01000230.onnx"
batch_size = 128
executor = { type = "tensorrt", max_batch_size = 128, pool_size = 32 }

[[inference]]
name = "01460343"
model_path = "s3://alpha-blokus/half/models/01460343.onnx"
batch_size = 128
executor = { type = "tensorrt", max_batch_size = 128, pool_size = 32 }

[[agents.QuadArena]]
name = "random"
type = "random"

[[agents.QuadArena]]
name = "mcts_00500124"
type = "mcts"
inference_config_name = "00500124"
fast_move_probability = 0.8
fast_move_num_rollouts = 100
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0.25
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 10
move_selection_temperature = 0.3

[[agents.QuadArena]]
name = "mcts_01000230"
type = "mcts"
inference_config_name = "01000230"
fast_move_probability = 0.8
fast_move_num_rollouts = 100
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0.25
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 10
move_selection_temperature = 0.3

[[agents.QuadArena]]
name = "mcts_01460343"
type = "mcts"
inference_config_name = "01460343"
fast_move_probability = 0.8
fast_move_num_rollouts = 100
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0.25
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 10
move_selection_temperature = 0.3

[game]
board_size = 10
num_moves = 6233
num_pieces = 21
num_piece_orientations = 91
move_data_file = "static/move_data/half.bin"
