num_concurrent_games = 10

[mcts_recorder]
data_directory = "/tmp/alphablokus_self_play_tiny/games"
flush_row_count = 10

[[inference]]
name = "default"
model_path = "static/networks/trivial_net_tiny.onnx"
batch_size = 2
executor = { type = "ort" }

[agents]
Single = { Random = { } }

[game]
board_size = 5
num_moves = 958
num_pieces = 21
num_piece_orientations = 91
move_data_file = "static/move_data/tiny.bin"
