[game]
board_size = 10
num_moves = 6233
num_pieces = 21
num_piece_orientations = 91
move_data_file = "static/move_data/half.bin"

[[inference]]
name = "default"
model_path = "s3://alpha-blokus/half/models"
batch_size = 1
executor = { type = "ort" }

[[agents]]
type = "random"
name = "random"

[[agents]]
type = "mcts"
name = "mcts"
fast_move_probability = 0.0
fast_move_num_rollouts = 500
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
# Play with noise 0 to skip exploration
root_dirichlet_noise_fraction = 0
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 0
# Play with temperature 0 to select the best move always
move_selection_temperature = 0.0
inference_config_name = "default"
