num_concurrent_games = 1024
duration_seconds = 1800

[observability.metrics]
type = "prometheus"

[observability.logging]
type = "console"

[mcts_recorder]
type = "disabled"

[[inference]]
name = "default"
model_path = "s3://alpha-blokus/full/models/04413189.onnx"
batch_size = 16
executor = { type = "tensorrt", max_batch_size = 16, pool_size = 32 }

[[inference]]
name = "invalid_considered"
model_path = "s3://alpha-blokus/full/models_simulated/04413189invalid_considered_1767019757.onnx"
batch_size = 16
executor = { type = "tensorrt", max_batch_size = 16, pool_size = 32 }

[[inference]]
name = "invalid_ignored_1"
model_path = "s3://alpha-blokus/full/models_simulated/04413189invalid_ignored_1767006076.onnx"
batch_size = 16
executor = { type = "tensorrt", max_batch_size = 16, pool_size = 32 }

[[inference]]
name = "invalid_ignored_2"
model_path = "s3://alpha-blokus/full/models_simulated/04413189invalid_ignored_1767034856.onnx"
batch_size = 16
executor = { type = "tensorrt", max_batch_size = 16, pool_size = 32 }

[[agents.QuadArena]]
type = "mcts"
name = "default"
fast_move_probability = 0.8
fast_move_num_rollouts = 100
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0.25
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 35
move_selection_temperature = 1.0
inference_config_name = "default"

[[agents.QuadArena]]
type = "mcts"
name = "invalid_considered"
fast_move_probability = 0.8
fast_move_num_rollouts = 100
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0.25
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 35
move_selection_temperature = 1.0
inference_config_name = "invalid_considered"

[[agents.QuadArena]]
type = "mcts"
name = "invalid_ignored_1"
fast_move_probability = 0.8
fast_move_num_rollouts = 100
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0.25
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 35
move_selection_temperature = 1.0
inference_config_name = "invalid_ignored_1"

[[agents.QuadArena]]
type = "mcts"
name = "invalid_ignored_2"
fast_move_probability = 0.8
fast_move_num_rollouts = 100
full_move_num_rollouts = 500
total_dirichlet_noise_alpha = 10.83
root_dirichlet_noise_fraction = 0.25
ucb_exploration_factor = 1.05
temperature_turn_cutoff = 35
move_selection_temperature = 1.0
inference_config_name = "invalid_ignored_2"

[game]
board_size = 20
num_moves = 30433
num_pieces = 21
num_piece_orientations = 91
move_data_file = "static/move_data/full.bin"

