num_concurrent_threads = 256
duration_seconds = 10

[game]
board_size = 20
num_moves = 30433
num_pieces = 21
num_piece_orientations = 91
move_data_file = "static/move_data/full.bin"

[inference]
name = "default"
model_path = "s3://alpha-blokus/full_v2/models_simulated/standalone_conv_value_position_1767949154.onnx"
batch_size = 128
executor = { type = "ort", execution_provider = "cpu" }
